@echo off
echo Creating file O...
powershell -Command "$myFile = (gc 'Testdata concepten local.ttl') -replace 'http://localhost:8080', 'http://data.ontwikkeling.pdok.nl'; [System.IO.File]::WriteAllLines('Testdata concepten O.ttl', $myFile)"
echo Creating file T...
powershell -Command "$myFile = (gc 'Testdata concepten local.ttl') -replace 'http://localhost:8080', 'http://data.test.pdok.nl'; [System.IO.File]::WriteAllLines('Testdata concepten T.ttl', $myFile)"
echo Creating file A...
powershell -Command "$myFile = (gc 'Testdata concepten local.ttl') -replace 'http://localhost:8080', 'http://data.acceptatie.pdok.nl'; [System.IO.File]::WriteAllLines('Testdata concepten A.ttl', $myFile)"
echo Creating file Catalogus 2.0 local...
powershell -Command "$myFile = (gc 'Testdata concepten local.ttl') -replace 'http://localhost:8080/catalogus/dso', 'http://localhost:8080'; [System.IO.File]::WriteAllLines('Testdata concepten Cat2.0 local.ttl', $myFile)"
echo Creating file Catalogus 2.0 T...
powershell -Command "$myFile = (gc 'Testdata concepten local.ttl') -replace 'http://localhost:8080/catalogus/dso', 'http://inu619.in.kadaster.nl'; [System.IO.File]::WriteAllLines('Testdata concepten Cat2.0 T.ttl', $myFile)"
echo Whoohoo! All done!
pause