@echo off
echo Creating concatenated file O...
powershell -Command "$myFile = (gc 'Concepten Tax local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.so.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('Concepten Tax O.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'Concepten Tax local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('Concepten Tax T.ttl', $myFile)"
echo Creating concatenated file A...
powershell -Command "$myFile = (gc 'Concepten Tax local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.fto.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('Concepten Tax A.ttl', $myFile)"
echo Creating concatenated file P...
powershell -Command "$myFile = (gc 'Concepten Tax local.ttl') -replace 'http://localhost:8080', 'http://tax.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('Concepten Tax P.ttl', $myFile)"
echo Whoohoo! All done!
pause