@echo off
echo Creating DatasetsDetail file T...
powershell -Command "$myFile = (gc 'DatasetsDetail local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('DatasetsDetail.ttl', $myFile)"
echo Creating DatasetsDetailHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'DatasetsDetailHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('DatasetsDetailHerhaaldeUpload.ttl', $myFile)"
echo Creating LoopingRapportage file T...
powershell -Command "$myFile = (gc 'LoopingRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('LoopingRapportage.ttl', $myFile)"
echo Creating LoopingRapportageHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'LoopingRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('LoopingRapportageHerhaaldeUpload.ttl', $myFile)"
echo Creating MissingLinksRapportage file T...
powershell -Command "$myFile = (gc 'MissingLinksRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('MissingLinksRapportage.ttl', $myFile)"
echo Creating MissingLinksRapportageHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'MissingLinksRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('MissingLinksRapportageHerhaaldeUpload.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageAfgekeurd file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageAfgekeurd local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageAfgekeurd.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageGevalideerd file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageGevalideerd local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageGevalideerd.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageGeverifieerd file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageGeverifieerd local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageGeverifieerd.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageNietBeoordeeld file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageNietBeoordeeld local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageNietBeoordeeld.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageTerAfkeuring file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageTerAfkeuring local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageTerAfkeuring.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageTerValidatie file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageTerValidatie local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageTerValidatie.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageUpdate file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageUpdate local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageUpdate.ttl', $myFile)"
echo Creating NietGevalideerdeLinksRapportageUpdateStart file T...
powershell -Command "$myFile = (gc 'NietGevalideerdeLinksRapportageUpdateStart local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('NietGevalideerdeLinksRapportageUpdateStart.ttl', $myFile)"
echo Creating RelatiecontroleRapportage file T...
powershell -Command "$myFile = (gc 'RelatiecontroleRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('RelatiecontroleRapportage.ttl', $myFile)"
echo Creating RelatiecontroleRapportageHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'RelatiecontroleRapportageHerhaaldeupload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('RelatiecontroleRapportageHerhaaldeupload.ttl', $myFile)"
echo Creating StatuscontroleRapportage file T...
powershell -Command "$myFile = (gc 'StatuscontroleRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('StatuscontroleRapportage.ttl', $myFile)"
echo Creating StatuscontroleRapportageHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'StatuscontroleRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('StatuscontroleRapportageHerhaaldeUpload.ttl', $myFile)"
echo Creating UploadConcepten file T...
powershell -Command "$myFile = (gc 'UploadConcepten local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadConcepten.ttl', $myFile)"
echo Creating UploadDataset file T...
powershell -Command "$myFile = (gc 'UploadDataset local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadDataset.ttl', $myFile)"
echo Creating UploadStatus file T...
powershell -Command "$myFile = (gc 'UploadStatus local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadStatus.ttl', $myFile)"
echo Creating WhereUsedRapportage file T...
powershell -Command "$myFile = (gc 'WhereUsedRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('WhereUsedRapportage.ttl', $myFile)"
echo Creating WhereUsedRapportageHerhaaldeUpload file T...
powershell -Command "$myFile = (gc 'WhereUsedRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('WhereUsedRapportageHerhaaldeUpload.ttl', $myFile)"

echo Whoohoo! All done!
pause