@echo off
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'DatasetsDetail local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('DatasetsDetail.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'DatasetsDetailHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('DatasetsDetailHerhaaldeUpload.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'StatuscontroleRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('StatuscontroleRapportage.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'StatuscontroleRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('StatuscontroleRapportageHerhaaldeUpload.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'RelatiecontroleRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('RelatiecontroleRapportage.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'RelatiecontroleRapportageHerhaaldeupload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('RelatiecontroleRapportageHerhaaldeupload.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'UploadConcepten local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadConcepten.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'UploadDataset local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadDataset.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'UploadStatus local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('UploadStatus.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'MissingLinksRapportage local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('MissingLinksRapportage.ttl', $myFile)"
echo Creating concatenated file T...
powershell -Command "$myFile = (gc 'MissingLinksRapportageHerhaaldeUpload local.ttl') -replace 'http://localhost:8080', 'http://pdok-ld-gck.in.kadaster.nl' -replace '/catalogus/tax(|/)$', '/(|/)$' -replace '/catalogus/tax', '' -replace '/catalogus', ''; [System.IO.File]::WriteAllLines('MissingLinksRapportageHerhaaldeUpload.ttl', $myFile)"

echo Whoohoo! All done!
pause